/**
 * Generated by MicroLang
 */
package microservices.proxy;

import microservices.AnimalService;
import lib.HttpUtil;
import java.io.IOException;

public class AnimalServiceProxy implements AnimalService {
	
	private HttpUtil util = new HttpUtil();
	
	@Override
	public boolean getIsdog(int id) {
		try {
			String response = util.sendRequest("http://" + HOST + ":" + PORT + "/isDog/" + id + "", "GET", "");
			return Boolean.valueOf(response);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
		return false;
	}
	
}
