/**
 * Generated by MicroLang
 */
package impl;

import microservices.abstr.AbstractAnimalService;

public class AnimalServiceImpl extends AbstractAnimalService {
	
	@Override
	public boolean getIsdog(int id) {
		//TODO: implement endpoint logic here
		return false;
	}
	
	public static void main(String[] args) {
		new AnimalServiceImpl().run();
	}

}
