/**
 * Generated by MicroLang
 */
package impl;

import microservices.abstr.AbstractService;

public class ServiceImpl extends AbstractService {
	
	public static void main(String[] args) {
		new ServiceImpl().run();
	}

}
